buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url "https://api.rikka.app/maven" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.0.0'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.0'
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}