plugins {
    id 'com.android.application'
}

android {
    namespace 'com.phx.shizuku.dominator'
    compileSdk 34
    defaultConfig {
        applicationId "com.phx.shizuku.dominator"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0-DOMINATOR"
    }
}

dependencies {
    implementation "dev.rikka.shizuku:api:13.1.0"
    implementation "dev.rikka.shizuku:provider:13.1.0"
}
